### ISSUE TITLE
lift up feature

### ISSUE THREAD

**Issue by WongIong** [AlonsoAliaga/BetterRevive#8]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
when player is down, others can lift him up and move him to a safe place instead of just reviving him at the dangerous sense.

**Describe alternatives you've considered**
no

**Additional context**
victim can‘t get off by himself (can‘t sneak to get off)

**Comment by AlonsoAliaga** [comment]
Sorry but due to how the plugin works right now to make the player down while bleeding this is simply not possible.

**Comment by WongIong** [comment]
Sorry, Maybe I described it not really well. What i meant is when player get into revive-status (lay down on the ground), other players can make that player to sit on their heads.

with this description, is it still not able to implement?

**Comment by AlonsoAliaga** [comment]
It is possible with a recode but i dont have plans to implement it tbh due to the huge errors it would cause (unsit cancel is broken in 1.16+ versions), additionally, moving the player would simply be hard to deal with tbh (as developer) while keeping support for 1.8.8 - 1.20.1, sorry, i cant implement something like that

**Comment by WongIong** [comment]
I agree with the developer point. But it is so sad to hear that. 
Anyways, thank you for answering me
